-- 코드를 입력하세요
SELECT P.WRITER_ID AS USER_ID, U.NICKNAME AS NICKNAME, P.TOTAL_PRICE AS TOTAL_PRICE
FROM (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE FROM USED_GOODS_BOARD     
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) AS P JOIN (
    SELECT USER_ID, NICKNAME FROM USED_GOODS_USER 
) AS U ON P.WRITER_ID = U.USER_ID
WHERE P.TOTAL_PRICE >= 700000
ORDER BY P.TOTAL_PRICE ASC;
