WITH RENTAL_COUNT AS (
    SELECT CAR_ID, EXTRACT(MONTH FROM START_DATE) AS MONTH, COUNT(CAR_ID) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD') AND START_DATE < TO_DATE('2022-12-01', 'YYYY-MM-DD')
    GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
),
TOTAL_COUNT AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD') AND START_DATE < TO_DATE('2022-12-01', 'YYYY-MM-DD')
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT A.MONTH, A.CAR_ID, A.RECORDS
FROM RENTAL_COUNT A JOIN TOTAL_COUNT B ON A.CAR_ID = B.CAR_ID
ORDER BY A.MONTH ASC, A.CAR_ID DESC;

