-- 코드를 작성해주세요
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM (SELECT ID, FISH_TYPE, LENGTH, ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RNK FROM FISH_INFO) AS FI
JOIN 
(SELECT FISH_TYPE, FISH_NAME FROM FISH_NAME_INFO) AS FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.RNK = 1
ORDER BY FI.ID;