-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(C.SALES) AS TOTAL_SALES
FROM (
    BOOK B JOIN BOOK_SALES C ON B.BOOK_ID = C.BOOK_ID
)
WHERE C.SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD') AND C.SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;