-- 코드를 입력하세요
SELECT M.CATEGORY, M.PRICE AS MAX_PRICE, N.PRODUCT_NAME
FROM (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AS M JOIN (
    SELECT PRICE, PRODUCT_NAME, CATEGORY
    FROM FOOD_PRODUCT    
) AS N ON M.CATEGORY = N.CATEGORY AND M.PRICE = N.PRICE
WHERE M.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY M.PRICE DESC;
